import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

function createPrisma() {
  const connectionString = process.env.DATABASE_URL!;
  const adapter = new PrismaPg({ connectionString });
  return new PrismaClient({ adapter } as any);
}

// Cars and insurance_estimates tables were removed in the schema simplification.
// Recommendations are now generated by the AI service and stored with inline car data.
async function main() {
  const prisma = createPrisma();
  try {
    console.log('Nothing to seed — car catalogue moved to AI-generated recommendations.');
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
